version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: elasticsearchdemo
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node