version: '3.1'

services:

  db:
    image: postgres:13.1-alpine
    container_name: postgresqldb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres




